apiVersion: v1
kind: Service
metadata:
  name: helmforrandom-service
spec:
  selector:
    app: helmforrandom
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: {{ .Values.service.type }}
